import asyncio
from datetime import datetime
from typing import Optional

XAI_REPORT_TEMPLATE = """
## Loan Intelligence Report
**Application ID:** {app_id}  
**Generated:** {timestamp}  
**Model Version:** LoanIQ v1.0 | Risk Model: XGBoost-v2.1 | Compliance Engine: RBI Circular Pack 2023

---

### Executive Summary

**Recommendation: {recommendation}**

This report has been prepared by the LoanIQ Co-pilot to assist the reviewing loan officer. All claims are grounded in submitted documents. The final credit decision remains with the authorized officer.

---

### Applicant Profile

- **Name:** {applicant_name} *(Source: PAN Card, Salary Slips)*
- **Monthly Income:** {monthly_income} *(Source: HDFC Bank Statement, Pages 2–4 — 6 consecutive months verified)*
- **Employer:** {employer} *(Source: Salary Slips — October 2025 to March 2026)*
- **Employment Tenure:** {employment_months} months *(Source: Employer Verification Letter)*
- **Loan Requested:** {loan_amount} over {loan_tenure} months

---

### Risk Assessment

| Metric | Value | Threshold | Status |
|--------|-------|-----------|--------|
| Credit Score | {credit_score} | ≥ 650 | {credit_status} |
| DSCR | {dscr} | ≥ 1.25 | {dscr_status} |
| FOIR | {foir} | ≤ 50% | {foir_status} |
| EMI | {emi}/month | — | — |
| Risk Tier | **{risk_tier}** | — | — |

**Risk Narrative:** The applicant demonstrates {risk_narrative}

---

### Compliance Status

| Rule ID | Check | Result |
|---------|-------|--------|
| KYC_001 | PAN Card Verification | ✅ PASS |
| KYC_002 | Aadhaar Linkage | ✅ PASS |
| KYC_003 | Address Proof | ✅ PASS |
| AML_001 | AML Watchlist | ✅ CLEAR |
| FOIR_001 | FOIR within RBI limits | {foir_compliance} |
| DSCR_001 | Debt Service Coverage | {dscr_compliance} |
| CIBIL_001 | Minimum Credit Score | {cibil_compliance} |
| DPDP_001 | Data Processing Consent | ✅ PASS |

**Compliance Score: {compliance_score}** — {compliance_narrative}

---

### Flags Requiring Officer Attention

{flags_section}

---

### Decision Rationale

{decision_rationale}

---

### Officer Instructions

This is a **co-pilot recommendation**. The loan officer must:
1. Review all flagged items above
2. Apply independent judgment on any ambiguous factors
3. Document rationale if overriding this recommendation
4. Ensure all physical documents are collected before disbursement

**Officer:** _________________________  
**Date of Review:** _________________________  
**Decision:** ☐ Approved  ☐ Conditionally Approved  ☐ Rejected  
**Override Reason (if applicable):** _________________________

---
*This report was generated by LoanIQ AI Co-pilot. It is a recommendation aid, not a legal decision document. The authorized loan officer retains full responsibility for the final credit decision per RBI AI Governance Guidelines 2024.*
"""

def generate_xai_report(session_id: str, doc_data: dict, risk_data: dict, compliance_data: dict) -> dict:
    """Generate the structured XAI report with robust numeric fallbacks."""
    recommendation = _determine_recommendation(risk_data, compliance_data, doc_data)
    
    # Target and wrap metrics securely to avoid TypeError runtime string crashes
    try:
        credit_score = int(risk_data.get("credit_score", 0))
    except (ValueError, TypeError):
        credit_score = 0

    try:
        dscr = float(risk_data.get("dscr", 0.0))
    except (ValueError, TypeError):
        dscr = 0.0

    try:
        foir = float(risk_data.get("foir", 1.0))
    except (ValueError, TypeError):
        foir = 1.0
        
    risk_tier = risk_data.get("risk_tier", "Unknown")
    
    # Build flags section Safely
    flags = []
    if not doc_data.get("property_valuation"):
        flags.append("⚠️  **Property valuation document missing** — Required before final disbursement. Request from applicant.")
    
    for rule in compliance_data.get("blocking_issues", []):
        flags.append(f"🚨 **{rule.get('name', 'Rule Fail')}** — {rule.get('message', '')} *(Ref: {rule.get('reference', 'N/A')})*")
    
    for rule in compliance_data.get("advisories", []):
        flags.append(f"💡 **Advisory: {rule.get('name', 'Note')}** — {rule.get('message', '')}")
    
    flags_section = "\n".join(f"- {f}" for f in flags) if flags else "✅ No critical flags. Proceed with standard documentation verification."
    
    # Formatted numeric representations safely structured
    try:
        monthly_income_val = int(doc_data.get('monthly_income', 0))
        monthly_income_str = f"₹{monthly_income_val:,}"
    except (ValueError, TypeError):
        monthly_income_str = "₹0"

    try:
        loan_amt_val = int(doc_data.get('loan_amount_requested', 0))
        loan_amt_str = f"₹{loan_amt_val:,}"
    except (ValueError, TypeError):
        loan_amt_str = "₹0"

    try:
        emi_val = int(risk_data.get('emi_monthly', 0))
        emi_str = f"₹{emi_val:,}"
    except (ValueError, TypeError):
        emi_str = f"₹0"

    report_text = XAI_REPORT_TEMPLATE.format(
        app_id=session_id[:8].upper(),
        timestamp=datetime.now().strftime("%d %b %Y, %I:%M %p"),
        recommendation=recommendation,
        applicant_name=doc_data.get("applicant_name", "N/A"),
        monthly_income=monthly_income_str,
        employer=doc_data.get("employer", "N/A"),
        employment_months=doc_data.get("employment_months", 0),
        loan_amount=loan_amt_str,
        loan_tenure=doc_data.get("loan_tenure_months", 0),
        credit_score=credit_score,
        dscr=dscr,
        foir=f"{foir * 100:.1f}%",
        emi=emi_str,
        risk_tier=risk_tier,
        credit_status="✅ PASS" if credit_score >= 650 else "❌ FAIL",
        dscr_status="✅ PASS" if dscr >= 1.25 else "❌ FAIL",
        foir_status="✅ PASS" if foir <= 0.50 else "❌ FAIL",
        risk_narrative=_risk_narrative(risk_tier, credit_score, dscr),
        foir_compliance="✅ PASS" if foir <= 0.50 else "❌ FAIL",
        dscr_compliance="✅ PASS" if dscr >= 1.25 else "❌ FAIL",
        cibil_compliance="✅ PASS" if credit_score >= 650 else "❌ FAIL",
        compliance_score=f"{compliance_data.get('compliance_score', 0)}%",
        compliance_narrative=_compliance_narrative(compliance_data),
        flags_section=flags_section,
        decision_rationale=_decision_rationale(recommendation, risk_data, compliance_data, doc_data),
    )
    
    return {
        "recommendation": recommendation,
        "report_text": report_text,
        "report_sections": {
            "applicant_profile": True,
            "risk_assessment": True,
            "compliance_status": True,
            "flags": flags,
            "decision_rationale": True,
        },
        "metadata": {
            "session_id": session_id,
            "generated_at": datetime.now().isoformat(),
            "model_version": "LoanIQ v1.0",
        }
    }

def _determine_recommendation(risk_data: dict, compliance_data: dict, doc_data: dict) -> str:
    # Explicit integer conversions to guarantee accurate length comparison evaluations
    failed_blocking_count = compliance_data.get("failed_blocking", 0)
    if isinstance(failed_blocking_count, list):
        failed_blocking_count = len(failed_blocking_count)
        
    if failed_blocking_count > 0:
        return "❌ DECLINE — Blocking compliance issues present"
    
    risk_tier = risk_data.get("risk_tier", "High")
    has_flags = not doc_data.get("property_valuation")
    
    try:
        comp_score = float(compliance_data.get("compliance_score", 0))
    except (ValueError, TypeError):
        comp_score = 0.0
    
    if risk_tier in ["Low", "Low-Medium"] and comp_score >= 85:
        if has_flags:
            return "⚠️ CONDITIONAL APPROVAL — Pending: property valuation document"
        return "✅ APPROVE — Strong risk profile, full compliance"
    elif risk_tier == "Medium":
        return "⚠️ CONDITIONAL APPROVAL — Review advisories with officer judgment"
    else:
        return "❌ DECLINE — Risk profile does not meet lending criteria"

def _risk_narrative(risk_tier: str, credit_score: int, dscr: float) -> str:
    if risk_tier in ["Low", "Low-Medium"]:
        return f"strong creditworthiness with a CIBIL score of {credit_score} and a DSCR of {dscr}, indicating comfortable repayment capacity well above the RBI minimum of 1.25x."
    elif risk_tier == "Medium":
        return f"acceptable risk parameters. Credit score {credit_score} meets eligibility. DSCR of {dscr} is within acceptable range but leaves limited buffer."
    else:
        return f"elevated risk. Credit score {credit_score} and DSCR {dscr} indicate potential repayment stress."

def _compliance_narrative(compliance_data: dict) -> str:
    score = compliance_data.get("compliance_score", 0)
    blocking = compliance_data.get("failed_blocking", 0)
    blocking_count = len(blocking) if isinstance(blocking, list) else blocking
    
    if blocking_count == 0 and score >= 85:
        return "All mandatory RBI checks passed. Advisory items noted for officer review."
    elif blocking_count == 0:
        return "Mandatory checks passed. Advisory flags require officer evaluation."
    else:
        return f"{blocking_count} blocking compliance issue(s) identified. Loan cannot proceed without resolution."

def _decision_rationale(recommendation: str, risk_data: dict, compliance_data: dict, doc_data: dict) -> str:
    factors = risk_data.get("risk_factors", [])
    positives = [f["text"] for f in factors if f.get("type") == "positive"]
    negatives = [f["text"] for f in factors if f.get("type") == "negative"]
    
    rationale = f"**Recommendation basis:** {recommendation}\n\n"
    
    if positives:
        rationale += "**Supporting factors:**\n"
        rationale += "\n".join(f"- {p}" for p in positives) + "\n\n"
    
    if negatives:
        rationale += "**Risk factors / concerns:**\n"
        rationale += "\n".join(f"- {n}" for n in negatives) + "\n\n"
    
    if not doc_data.get("property_valuation"):
        rationale += "**Critical item:** Property valuation document must be collected prior to disbursement per RBI Mortgage Guidelines. Conditional approval is recommended pending this document.\n"
    
    return rationale

async def run_decision_agent(session_id: str, doc_data: dict, risk_data: dict, compliance_data: dict, callback) -> dict:
    """Decision Agent — generates streaming XAI report."""
    steps = [
        (0.5, "📝 Aggregating findings from all agents..."),
        (1.0, "🔗 Cross-referencing document citations..."),
        (1.2, "🤔 Formulating recommendation rationale..."),
        (1.5, "✍️  Generating explainable AI report..."),
        (0.8, "📋 Formatting officer brief..."),
        (0.4, "✅ Report ready for officer review"),
    ]
    
    for delay, message in steps:
        await asyncio.sleep(delay)
        await callback({
            "agent": "decision",
            "status": "running",
            "message": message,
            "session_id": session_id
        })
    
    report = generate_xai_report(session_id, doc_data, risk_data, compliance_data)
    
    result = {
        "agent": "decision",
        "status": "complete",
        "data": report,
        "session_id": session_id,
        "summary": {
            "recommendation": report["recommendation"],
            "report_ready": True,
        }
    }
    
    await callback(result)
    return report